name: Build Executable

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags

jobs:
  build:
    runs-on: windows-latest
    # CORRECT PERMISSIONS FOR RELEASES
    permissions:
      contents: write  # Required for creating releases

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        
    - name: Build executable
      run: |
        pyinstaller --onefile --noconsole --name file_organizer file_organizer.py
        
    - name: Verify build output
      run: dir dist\  # Windows directory listing for debugging
        
    - name: Upload release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/file_organizer.exe  # FIXED SPELLING
      if: startsWith(github.ref, 'refs/tags/')
